version: "3.7"

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    networks:
      - pacco
    # volumes:
    #   - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - pacco
    ports:
    - 9998:9998
    - 9999:9999

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    ports:
      - 8200:8200
    networks:
      - pacco
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK

networks:
  pacco:
    name: pacco-network
    external: true

# volumes:
#   consul:
#     driver: local