version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - pacco
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - pacco
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - pacco
    volumes: 
      - redis:/data

networks:
  pacco:
    name: pacco-network

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local