version: "3.7"

services:
  api-gateway:
    build: ../Pacco.APIGateway
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada.docker
    ports:
      - 5000:80
    networks:
      - pacco

  availability-service:
    build: ../Pacco.Services.Availability
    container_name: availability-service
    restart: unless-stopped
    ports:
      - 5001:80 
    networks:
      - pacco

  customers-service:
    build: ../Pacco.Services.Customers
    container_name: customers-service
    restart: unless-stopped
    ports:
      - 5002:80
    networks:
      - pacco

  deliveries-service:
    build: ../Pacco.Services.Deliveries
    container_name: deliveries-service
    restart: unless-stopped
    ports:
      - 5003:80
    networks:
      - pacco

  identity-service:
    build: ../Pacco.Services.Identity
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5004:80
    networks:
      - pacco

  operations-service:
    build: ../Pacco.Services.Operations
    container_name: operations-service
    restart: unless-stopped
    ports:
      - 5005:80
    networks:
      - pacco
    depends_on:
      - availability-service
      - customers-service
      - deliveries-service
      - identity-service
      - orders-service
      - ordermaker-service
      - parcels-service
      - vehicles-service

  orders-service:
    build: ../Pacco.Services.Orders
    container_name: orders-service
    restart: unless-stopped
    ports:
      - 5006:80
    networks:
      - pacco

  ordermaker-service:
    build: ../Pacco.Services.OrderMaker
    container_name: ordermaker-service
    restart: unless-stopped
    ports:
      - 5015:80
    networks:
      - pacco

  parcels-service:
    build: ../Pacco.Services.Parcels
    container_name: parcels-service
    restart: unless-stopped
    ports:
      - 5007:80
    networks:
      - pacco

  pricing-service:
    build: ../Pacco.Services.Pricing
    container_name: pricing-service
    restart: unless-stopped
    ports:
      - 5008:80
    networks:
      - pacco

  vehicles-service:
    build: ../Pacco.Services.Vehicles
    container_name: vehicles-service
    restart: unless-stopped
    ports:
      - 5009:80
    networks:
      - pacco

networks:
  pacco:
    name: pacco-network
    external: true